configuration-set.web-sauce.profiles=web/headless/chrome/1920x1080
configuration-set.web-sauce.suites=web_app
configuration-set.web-sauce.environments=sauce

configuration-set.api-sauce.profiles=
configuration-set.api-sauce.suites=rest_api
configuration-set.api-sauce.environments=api
